#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi
LINKFLAGS="-X github.com/rancher/portexporter.Version=$VERSION"
LINKFLAGS="-X github.com/rancher/portexporter.GitCommit=$COMMIT $LINKFLAGS"
CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o bin/portexporter
GOOS=linux go build -ldflags "$LINKFLAGS" -o bin/portexporter-linux
GOOS=darwin go build -ldflags "$LINKFLAGS" -o bin/portexporter-darwin
GOOS=windows go build -ldflags "$LINKFLAGS" -o bin/portexporter-windows
